###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    postgres:
        image: 'postgres:11.1-alpine'
        working_dir: /app
        volumes:
            - '.:/app'
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=123456
            - POSTGRES_DB=assemble_db
        ports:
            - '5559:5432'

    webserver:
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - '.:/app'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '5555:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /app
        volumes:
            - '.:/app'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
